window.allSeries = [
    {
        id: 1,
        title: "Charmed - Zauberhafte Hexen",
        description: "Die erste Luminox-Serie!",
        genre: "Fantasy",
        year: 1998,
        creator_name: "Aaron Spellings Firma",
        thumbnail_url: "allvideos/thumbnails/serie1.jpg",
        seasons: [
            {
                season: 1,
                episodes: [
                    { episode: 1,  title: "Das Buch der Schatten", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQSha1jaFRgYT5-c73C75GsQAXYNY9LZDG3YI8-ykFFYSE4", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (1).jpg", description: "Die allererste Folge!" },
                    { episode: 2,  title: "Teuflische Augen", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQQej8-9_5zwSrv_TOSrLmm7Adr3dFMeQfcfKwC62qiPhV0", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (2).jpg", description: "Die Reise beginnt." },
                    { episode: 3,  title: "Die Formwandler", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQRLfOeo4OzuRpSToXBgh7gQAS6wmtguWhWfQhefwwaQpAg", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (3).jpg", description: "Die Reise beginnt." },
                    { episode: 4,  title: "Rendezvous mit einem Geist", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQRH4CI4N7XRRKvFEsYr6Op3AWrz2YSdRdBcxV-vyI_tgPo", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (4).jpg", description: "Die Reise beginnt." },
                    { episode: 5,  title: "Tödliche Träume", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQSCyi0MY2ENSoq-m8-vnavrAf8TZYh0N55mtfnF8ckQ5J0", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (5).jpg", description: "Die Reise beginnt." },
                    { episode: 6,  title: "Höllenhochzeit", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQSaiMbgMCjRRL50MrOIMsTIATm1vWwm1PPjeBGvcAj9e5E", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (6).jpg", description: "Die Reise beginnt." },
                    { episode: 7,  title: "Schwester der Nacht", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQThpkvHu-26S41nn5ZHzjiCAbYksC7rZKbzkiRAkpjYb50", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (7).jpg", description: "Die Reise beginnt." },
                    { episode: 8,  title: "Der Wahrheitszauber", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQTM-aVUC82PRJbSohld8MHaARfo0E1H-yjzmHgyEytB9cs", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (8).jpg", description: "Die Reise beginnt." },
                    { episode: 9,  title: "Rückkehr aus dem Jenseits", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQSdpIud1Mc0Qb_mGcytTLAiAdBq3BPrsy4zGmjSmh5vorU", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (9).jpg", description: "Die Reise beginnt." },
                    { episode: 10, title: "Machtlos", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQQPqDOwzc4KR7iOReH0ol3PAb8LpVDF4eqZe0w65QwTWng", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (10).jpg", description: "Die Reise beginnt." },
                    { episode: 11, title: "Der Fluch der Urne", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQQIe8hYDEIaSZiBvUFuYWokAWq4w5A1KCSn_-PNe3zO2QY", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (11).jpg", description: "Die Reise beginnt." },
                    { episode: 12, title: "Wendigo", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQTPSYPQhZGaSabdrobGBgJMASbYXquTZtF8AaqIZFl1zhM", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (12).jpg", description: "Die Reise beginnt." },
                    { episode: 13, title: "Liebe ist die stärkste Macht", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQSVRsgbWV0JQZZhSOD-nF0LAd003VX4dn4Xk145VfXlblk", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (13).jpg", description: "Die Reise beginnt." },
                    { episode: 14, title: "Nachricht von Max", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQQORVNxtUb-R6vW-aFvZazEARmdkn6zCJqjbvWFe8ltCH8", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (14).jpg", description: "Die Reise beginnt." },
                    { episode: 15, title: "Wer hat Angst vorm Schwarzen Mann?", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQSBcU4t-I3JRZ66KKy-3fSIATjrWUPVoEgCkMFrxX-28X8", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (15).jpg", description: "Die Reise beginnt." },
                    { episode: 16, title: "Mann stirbt nur dreimal", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQRAEyShJuYlTJwj_sJ1SBgCAYAUeUs8Mz865QE-xAIovAE", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (16).jpg", description: "Die Reise beginnt." },
                    { episode: 17, title: "Zurück in die Vergangenheit", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQTa3d3R-R4oRaXzxLdfC6ggATADxeznzjOSGPNbRqPbP78", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (17).jpg", description: "Die Reise beginnt." },
                    { episode: 18, title: "Wenn das Böse erwacht", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQTLAhNHDDq2Q6ixUzaiJAz1AfW4zaJYICHrg4c9MrZYQ-o", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (18).jpg", description: "Die Reise beginnt." },
                    { episode: 19, title: "Blind", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQTTv7jH7e_0SbQ6SE_DeMeMAXyMRwo84uF5TdzGbZipf7E", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (19).jpg", description: "Die Reise beginnt." },
                    { episode: 20, title: "Ein Geist, zwei Schwestern", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQS9awpuOVFsSIka0nj0ltPqAdxXkJZaPcSB5usK5P7Quks", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (20).jpg", description: "Die Reise beginnt." },
                    { episode: 21, title: "Wächter der Dunkelheit", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQRUco8eiC01QIXA_R_qsBn6AXSCFAKYPbpUw0laOY5rptQ", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (21).jpg", description: "Die Reise beginnt." },
                    { episode: 22, title: "Immer wieder Mittwoch", video_url: "https://1drv.ms/v/c/f0d0150b189f1d96/IQQI5cxPz3cPT5cL9jPNymSxAXz11_IaaRxZA--IcEbMpzg", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 1/Folge (22).jpg", description: "Die Reise beginnt." }
                ]
            },
            {
                season: 2,
                episodes: [
                    { episode: 1,  title: "Abraxas", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (1).jpg", description: "Die allererste Folge!" },
                    { episode: 2,  title: "Hexenjagd", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (2).jpg", description: "Die Reise beginnt." },
                    { episode: 3,  title: "Voll Im Bild", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (3).jpg", description: "Die Reise beginnt." },
                    { episode: 4,  title: "Pakt mit dem Teufel", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (4).jpg", description: "Die Reise beginnt." },
                    { episode: 5,  title: "Einfach unwiderstehlich", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (5).jpg", description: "Die Reise beginnt." },
                    { episode: 6,  title: "Der Auserwählte", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (6).jpg", description: "Die Reise beginnt." },
                    { episode: 7,  title: "Die Akasha-Rollen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (7).jpg", description: "Die Reise beginnt." },
                    { episode: 8,  title: "Schrecken der Tiefe", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (8).jpg", description: "Die Reise beginnt." },
                    { episode: 9,  title: "Zwischen Himmel und Hölle", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (9).jpg", description: "Die Reise beginnt." },
                    { episode: 10, title: "Mitten ins Herz", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (10).jpg", description: "Die Reise beginnt." },
                    { episode: 11, title: "Drei Hexen und ein Baby", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (11).jpg", description: "Die Reise beginnt." },
                    { episode: 12, title: "Fieber", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (12).jpg", description: "Die Reise beginnt." },
                    { episode: 13, title: "Ein tierisch guter Spuk", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (13).jpg", description: "Die Reise beginnt." },
                    { episode: 14, title: "Verflucht in alle Ewigkeit", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (14).jpg", description: "Die Reise beginnt." },
                    { episode: 15, title: "Das Zeichen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (15).jpg", description: "Die Reise beginnt." },
                    { episode: 16, title: "Vom Pech verfolgt", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (16).jpg", description: "Die Reise beginnt." },
                    { episode: 17, title: "Ewige Jugend", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (17).jpg", description: "Die Reise beginnt." },
                    { episode: 18, title: "Der reinste Horror", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (18).jpg", description: "Die Reise beginnt." },
                    { episode: 19, title: "Ex Libris", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (19).jpg", description: "Die Reise beginnt." },
                    { episode: 20, title: "Hexenblut", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (20).jpg", description: "Die Reise beginnt." },
                    { episode: 21, title: "Die Reiter der Apokalypse", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (21).jpg", description: "Die Reise beginnt." },
                    { episode: 22, title: "Wünsch dir was", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 2/Folge (22).jpg", description: "Die Reise beginnt." }
                ]
            },
            {
                season: 3,
                episodes: [
                    { episode: 1,  title: "Die Verschwörung des Bösen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (1).jpg", description: "Die Reise beginnt." },
                    { episode: 2,  title: "Hexenhochzeit", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (2).jpg", description: "Die Reise beginnt." },
                    { episode: 3,  title: "Von Feen und Trollen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (3).jpg", description: "Die Reise beginnt." },
                    { episode: 4,  title: "Das Zeitportal", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (4).jpg", description: "Die Reise beginnt." },
                    { episode: 5,  title: "Die Dämonenfalle", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (5).jpg", description: "Die Reise beginnt." },
                    { episode: 6,  title: "Alle oder keine", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (6).jpg", description: "Die Reise beginnt." },
                    { episode: 7,  title: "Die Macht der Gefühle", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (7).jpg", description: "Die Reise beginnt." },
                    { episode: 8,  title: "Balthasar", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (8).jpg", description: "Die Reise beginnt." },
                    { episode: 9,  title: "Besessen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (9).jpg", description: "Die Reise beginnt." },
                    { episode: 10, title: "Wenn der Elsmann kommt", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (10).jpg", description: "Die Reise beginnt." },
                    { episode: 11, title: "Gegen alle Regeln", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (11).jpg", description: "Die Reise beginnt." },
                    { episode: 12, title: "Verlorene Seelen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (12).jpg", description: "Die Reise beginnt." },
                    { episode: 13, title: "Das Böse in mir", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (13).jpg", description: "Die Reise beginnt." },
                    { episode: 14, title: "Stadt der Geister", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (14).jpg", description: "Die Reise beginnt." },
                    { episode: 15, title: "Trauung mit Hindernissen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (15).jpg", description: "Die Reise beginnt." },
                    { episode: 16, title: "Der Tod siegt immer", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (16).jpg", description: "Die Reise beginnt." },
                    { episode: 17, title: "Aller guten Dinge sind neun", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (17).jpg", description: "Die Reise beginnt." },
                    { episode: 18, title: "Die sieben Todsünden", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (18).jpg", description: "Die Reise beginnt." },
                    { episode: 19, title: "Die Bruderschaft", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (19).jpg", description: "Die Reise beginnt." },
                    { episode: 20, title: "Freund oder Feind?", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (20).jpg", description: "Die Reise beginnt." },
                    { episode: 21, title: "Die Todesfee", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (21).jpg", description: "Die Reise beginnt." },
                    { episode: 22, title: "Das Ende", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 3/Folge (22).jpg", description: "Die Reise beginnt." }
                ]
            },
            {
                season: 4,
                episodes: [
                    { episode: 1,  title: "Die neue Macht der Drei + 48 Stunden", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (1).jpg", description: "Die Reise beginnt." },
                    { episode: 2,  title: "Hexenhochzeit", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (2).jpg", description: "Die Reise beginnt." },
                    { episode: 3,  title: "Die drei Furien", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (3).jpg", description: "Die Reise beginnt." },
                    { episode: 4,  title: "Der Mann mit dem Drachendolch", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (4).jpg", description: "Die Reise beginnt." },
                    { episode: 5,  title: "Der Sammler", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (5).jpg", description: "Die Reise beginnt." },
                    { episode: 6,  title: "Ein Prinz für Paige", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (6).jpg", description: "Die Reise beginnt." },
                    { episode: 7,  title: "Hirngespinste", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (7).jpg", description: "Die Reise beginnt." },
                    { episode: 8,  title: "Schwarz wie der Teufel", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (8).jpg", description: "Die Reise beginnt." },
                    { episode: 9,  title: "Der Ring der Musen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (9).jpg", description: "Die Reise beginnt." },
                    { episode: 10, title: "Geister der Vergangenheit", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (10).jpg", description: "Die Reise beginnt." },
                    { episode: 11, title: "Die zwölf Geschworenen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (11).jpg", description: "Die Reise beginnt." },
                    { episode: 12, title: "Feuer", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (12).jpg", description: "Die Reise beginnt." },
                    { episode: 13, title: "Das Schwarze Nichts", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (13).jpg", description: "Die Reise beginnt." },
                    { episode: 14, title: "Die Frage aller Fragen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (14).jpg", description: "Die Reise beginnt." },
                    { episode: 15, title: "Die Braut trägt Schwarz", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (15).jpg", description: "Die Reise beginnt." },
                    { episode: 16, title: "Das fünfte Rad", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (16).jpg", description: "Die Reise beginnt." },
                    { episode: 17, title: "Der Soldat Leo Wyatt", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (17).jpg", description: "Die Reise beginnt." },
                    { episode: 18, title: "Beiß mich", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (18).jpg", description: "Die Reise beginnt." },
                    { episode: 19, title: "Die Krönung", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (19).jpg", description: "Die Reise beginnt." },
                    { episode: 20, title: "Lang lebe die Königin", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (20).jpg", description: "Die Reise beginnt." },
                    { episode: 21, title: "Die Brut des Bösen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (21).jpg", description: "Die Reise beginnt." },
                    { episode: 22, title: "Der Engel des Schicksals", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 4/Folge (22).jpg", description: "Die Reise beginnt." }
                ]
            },
            {
    season: 5,
    episodes: [
        { episode: 1,  title: "Der Ruf des Meeres (1+2)", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (1).jpg", description: "Die Reise beginnt." },
        { episode: 3,  title: "Und wenn sie nicht gestorben sind …", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (3).jpg", description: "Die Reise beginnt." },
        { episode: 4,  title: "Sirenengesang", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (4).jpg", description: "Die Reise beginnt." },
        { episode: 5,  title: "Superhelden", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (5).jpg", description: "Die Reise beginnt." },
        { episode: 6,  title: "Böse Augen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (6).jpg", description: "Die Reise beginnt." },
        { episode: 7,  title: "Barbas", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (7).jpg", description: "Die Reise beginnt." },
        { episode: 8,  title: "Tödliche Visionen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (8).jpg", description: "Die Reise beginnt." },
        { episode: 9,  title: "Unverwundbar", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (9).jpg", description: "Die Reise beginnt." },
        { episode: 10, title: "Mumienschanz", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (10).jpg", description: "Die Reise beginnt." },
        { episode: 11, title: "Der Nexus", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (11).jpg", description: "Die Reise beginnt." },
        { episode: 12, title: "Happy Birthday, Cole", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (12).jpg", description: "Die Reise beginnt." },
        { episode: 13, title: "Quälgeister", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (13).jpg", description: "Die Reise beginnt." },
        { episode: 14, title: "San Francisco träumt", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (14).jpg", description: "Die Reise beginnt." },
        { episode: 15, title: "Ein magisches Geschenk", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (15).jpg", description: "Die Reise beginnt." },
        { episode: 16, title: "Babyalarm", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (16).jpg", description: "Die Reise beginnt." },
        { episode: 17, title: "Glücksbringer", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (17).jpg", description: "Die Reise beginnt." },
        { episode: 18, title: "Katzenjammer", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (18).jpg", description: "Die Reise beginnt." },
        { episode: 19, title: "Tanz um die ewige Quelle", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (19).jpg", description: "Die Reise beginnt." },
        { episode: 20, title: "Nichts sehen, nichts hören, nichts sagen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (20).jpg", description: "Die Reise beginnt." },
        { episode: 21, title: "Hexentaufe", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (21).jpg", description: "Die Reise beginnt." },
        { episode: 22, title: "Kampf der Titanen (1)", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 5/Folge (22).jpg", description: "Die Reise beginnt." }
    ]
},
{
    season: 6,
    episodes: [
        { episode: 1,  title: "Im Bann der Walküren (1)", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (1).jpg", description: "Die Reise beginnt." },
        { episode: 2,  title: "Im Bann der Walküren (2)", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (2).jpg", description: "Die Reise beginnt." },
        { episode: 3,  title: "Vergissmeinnicht", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (3).jpg", description: "Die Reise beginnt." },
        { episode: 4,  title: "Die Ohnmacht der Drei", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (4).jpg", description: "Die Reise beginnt." },
        { episode: 5,  title: "Tödliche Liebe", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (5).jpg", description: "Die Reise beginnt." },
        { episode: 6,  title: "Opfer der Sehnsucht", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (6).jpg", description: "Die Reise beginnt." },
        { episode: 7,  title: "Seelenqualen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (7).jpg", description: "Die Reise beginnt." },
        { episode: 8,  title: "Piper und die Tafelrunde", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (8).jpg", description: "Die Reise beginnt." },
        { episode: 9,  title: "Kleine Monster", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (9).jpg", description: "Die Reise beginnt." },
        { episode: 10, title: "Zwischen den Zeiten", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (10).jpg", description: "Die Reise beginnt." },
        { episode: 11, title: "Witchstock", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (11).jpg", description: "Die Reise beginnt." },
        { episode: 12, title: "Der perfekte Mann", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (12).jpg", description: "Die Reise beginnt." },
        { episode: 13, title: "Schlechtes Karma", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (13).jpg", description: "Die Reise beginnt." },
        { episode: 14, title: "Die kopflosen Drei", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (14).jpg", description: "Die Reise beginnt." },
        { episode: 15, title: "Bezaubernde Phoebe", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (15).jpg", description: "Die Reise beginnt." },
        { episode: 16, title: "Piper und Leo", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (16).jpg", description: "Die Reise beginnt." },
        { episode: 17, title: "Klassentreffen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (17).jpg", description: "Die Reise beginnt." },
        { episode: 18, title: "Die Spinne", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (18).jpg", description: "Die Reise beginnt." },
        { episode: 19, title: "Das Tribunal", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (19).jpg", description: "Die Reise beginnt." },
        { episode: 20, title: "Magische Männer", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (20).jpg", description: "Die Reise beginnt." },
        { episode: 21, title: "Witch Wars", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (21).jpg", description: "Die Reise beginnt." },
        { episode: 22, title: "Gute und böse Welt (1)", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 6/Folge (22).jpg", description: "Die Reise beginnt." }
    ]
},
{
    season: 7,
    episodes: [
        { episode: 1,  title: "Blinder Zorn", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (1).jpg", description: "Die Reise beginnt." },
        { episode: 2,  title: "Nackte Tatsachen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (2).jpg", description: "Die Reise beginnt." },
        { episode: 3,  title: "Der Rivalitätszauber", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (3).jpg", description: "Die Reise beginnt." },
        { episode: 4,  title: "Der Fluch der Piraten", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (4).jpg", description: "Die Reise beginnt." },
        { episode: 5,  title: "Todesengel", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (5).jpg", description: "Die Reise beginnt." },
        { episode: 6,  title: "Im Bann des Blauen Mondes", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (6).jpg", description: "Die Reise beginnt." },
        { episode: 7,  title: "Ohne Schutzengel", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (7).jpg", description: "Die Reise beginnt." },
        { episode: 8,  title: "Der burmesische Falke", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (8).jpg", description: "Die Reise beginnt." },
        { episode: 9,  title: "Was ist mit Leo los?", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (9).jpg", description: "Die Reise beginnt." },
        { episode: 10, title: "Ich sehe was, was du nicht siehst", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (10).jpg", description: "Die Reise beginnt." },
        { episode: 11, title: "Die Hexen von nebenan", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (11).jpg", description: "Die Reise beginnt." },
        { episode: 12, title: "Utopia Erwacht", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (12).jpg", description: "Die Reise beginnt." },
        { episode: 13, title: "Charmageddon", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (13).jpg", description: "Die Reise beginnt." },
        { episode: 14, title: "Carpe Dämon", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (14).jpg", description: "Die Reise beginnt." },
        { episode: 15, title: "Feuer und Flamme", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (15).jpg", description: "Die Reise beginnt." },
        { episode: 16, title: "Der verlorene Leo", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (16).jpg", description: "Die Reise beginnt." },
        { episode: 17, title: "Wer hat die Eltern geschrumpft", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (17).jpg", description: "Die Reise beginnt." },
        { episode: 18, title: "Die Büchse der Pandora", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (18).jpg", description: "Die Reise beginnt." },
        { episode: 19, title: "Freaky Phoebe", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (19).jpg", description: "Die Reise beginnt." },
        { episode: 20, title: "Mein Freund, der Dämon", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (20).jpg", description: "Die Reise beginnt." },
        { episode: 21, title: "Der Tod steht ihnen gut", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (21).jpg", description: "Die Reise beginnt." },
        { episode: 22, title: "Macht oder Leben", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 7/Folge (22).jpg", description: "Die Reise beginnt." }
    ]
},
{
    season: 8,
    episodes: [
        { episode: 1,  title: "Totgesagte leben länger", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (1).jpg", description: "Die Reise beginnt." },
        { episode: 2,  title: "Halliwells im Wunderland", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (2).jpg", description: "Die Reise beginnt." },
        { episode: 3,  title: "Lauf, Piper, lauf", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (3).jpg", description: "Die Reise beginnt." },
        { episode: 4,  title: "Verzweifelte Haushexen", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (4).jpg", description: "Die Reise beginnt." },
        { episode: 5,  title: "Entzauberte Julie", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (5).jpg", description: "Die Reise beginnt." },
        { episode: 6,  title: "Kill Billie: Vol.1", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (6).jpg", description: "Die Reise beginnt." },
        { episode: 7,  title: "Bitte lächeln", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (7).jpg", description: "Die Reise beginnt." },
        { episode: 8,  title: "Yin und Yang", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (8).jpg", description: "Die Reise beginnt." },
        { episode: 9,  title: "Blutsbande", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (9).jpg", description: "Die Reise beginnt." },
        { episode: 10, title: "Vaya Con Leos", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (10).jpg", description: "Die Reise beginnt." },
        { episode: 11, title: "Billies Killer-Eltern", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (11).jpg", description: "Die Reise beginnt." },
        { episode: 12, title: "Mit gleicher Münze", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (12).jpg", description: "Die Reise beginnt." },
        { episode: 13, title: "Klein, aber mein", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (13).jpg", description: "Die Reise beginnt." },
        { episode: 14, title: "Büffel, Tiger und Hund", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (14).jpg", description: "Die Reise beginnt." },
        { episode: 15, title: "Die letzte Versuchung von Christy", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (15).jpg", description: "Die Reise beginnt." },
        { episode: 16, title: "Verliebt, verlobt, verwirrt", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (16).jpg", description: "Die Reise beginnt." },
        { episode: 17, title: "Ein hoher Preis", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (17).jpg", description: "Die Reise beginnt." },
        { episode: 18, title: "Identitätskrise", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (18).jpg", description: "Die Reise beginnt." },
        { episode: 19, title: "Zeig mir deinen Traum", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (19).jpg", description: "Die Reise beginnt." },
        { episode: 20, title: "Hexenkampf", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (20).jpg", description: "Die Reise beginnt." },
        { episode: 21, title: "Kill Billie: Vol.2", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (21).jpg", description: "Die Reise beginnt." },
        { episode: 22, title: "Das Vermächtnis der Halliwells", video_url: "", thumbnail_url: "allvideos/Serien/Charmed - Zauberhafte Hexen/Staffel 8/Folge (22).jpg", description: "Die Reise beginnt." }
    ]
} // schließt Staffel 8 ab
] // schließt das seasons-Array ab
} // schließt das Serien-Objekt ab
]; // schließt das allSeries-Array ab
        
        